stress-ng test-script v15

diff --git a/lib/sh-test-lib b/lib/sh-test-lib
--- a/lib/sh-test-lib
+++ b/lib/sh-test-lib
@@ -385,80 +385,127 @@ generate_skipfile() {
 #Used to update test result in LAVA environment or locally
 #skip_list to skip rest testcases if prerequisite don't meet by making primary testcase fail and others skip
 lava_test_result() {
-	exit_code="$?"
-	[ "$#" -lt 1 ] && error_msg "Usage: lava_test_result test_case [skip_list]"
-	test_case="$1"
-	skip_list="$2"
-	which lava-test-runner
-	test_lava=$?
-	if [ "${test_lava}" -eq 0 ]; then
-		lava_check="true"
-	else
-		lava_check="false"
-	fi		
-	if [ "${exit_code}" -eq 0 ];then
-		if [ "${lava_check}" = "true" ];then
-			lava-test-case ${test_case} --result pass
-		else
-			echo "${test_case} test passed"
-		fi
-	else
-		if [ "${lava_check}" = "true" ];then
-			lava-test-case ${test_case} --result fail 
-			if [ -n "${skip_list}" ]; then
-				for i in ${skip_list}; do
-				lava-test-case ${i} --result skip  
-				done
-			fi
-	                exit 0
-		else
-			echo "${test_case} test failed"
-			if [ -n "${skip_list}" ]; then
+    exit_code="$?"
+    [ "$#" -lt 1 ] && error_msg "Usage: lava_test_result test_case [skip_list]"
+    test_case="$1"
+    skip_list="$2"
+    which lava-test-runner
+    test_lava=$?
+    if [ "${test_lava}" -eq 0 ]; then
+        lava_check="true"
+    else
+        lava_check="false"
+    fi      
+    if [ "${exit_code}" -eq 0 ];then
+        if [ "${lava_check}" = "true" ];then
+            lava-test-case ${test_case} --result pass
+        else
+            echo "${test_case} test passed"
+        fi
+    else
+        if [ "${lava_check}" = "true" ];then
+            lava-test-case ${test_case} --result fail 
+            if [ -n "${skip_list}" ]; then
+                for i in ${skip_list}; do
+                lava-test-case ${i} --result skip  
+                done
+            fi
+                    exit 0
+        else
+            echo "${test_case} test failed"
+            if [ -n "${skip_list}" ]; then
                                 for i in ${skip_list}; do
-                                	echo "${i} skip" 
+                                    echo "${i} skip" 
                                 done
                         fi
-			exit 0
+            exit 0
 
-		fi
-	fi
+        fi
+    fi
 }
 
 #skip_list to skip rest testcases if test step fails by making primary testcase fail and others skip
 exit_on_step_fail() {
-	exit_code="$?"
-	[ "$#" -lt 1 ] && error_msg "Usage: exit_on_step_fail test_case [skip_list]"
-	test_case="$1"
-	skip_list="$2"
-	if [ "${exit_code}" -eq 0 ];then
-		:
-	else
-		if [ `which lava-test-runner` ]; then
-			lava-test-case ${test_case} --result fail	 
-			if [ -n "${skip_list}" ]; then
-				for i in ${skip_list}; do
-				lava-test-case ${i} --result skip  
-				done
-			fi
-			exit 0
-		else
-			echo "${test_case} test failed"
-			if [ -n "${skip_list}" ]; then   
-				for i in ${skip_list}; do   
-				echo "${i} skip"
-				done
-			fi
-			exit 0
-		fi
-	fi
+    exit_code="$?"
+    [ "$#" -lt 1 ] && error_msg "Usage: exit_on_step_fail test_case [skip_list]"
+    test_case="$1"
+    skip_list="$2"
+    if [ "${exit_code}" -eq 0 ];then
+        :
+    else
+        if [ `which lava-test-runner` ]; then
+            lava-test-case ${test_case} --result fail    
+            if [ -n "${skip_list}" ]; then
+                for i in ${skip_list}; do
+                lava-test-case ${i} --result skip  
+                done
+            fi
+            exit 0
+        else
+            echo "${test_case} test failed"
+            if [ -n "${skip_list}" ]; then   
+                for i in ${skip_list}; do   
+                echo "${i} skip"
+                done
+            fi
+            exit 0
+        fi
+    fi
 }
 
 skip_test() {
-	test_case="$1"
-	if [ `which lava-test-runner` ]; then
-		lava-test-case ${test_case} --result skip
-	else
-		echo "${test_case} skip"
-	fi
+    test_case="$1"
+    if [ `which lava-test-runner` ]; then
+        lava-test-case ${test_case} --result skip
+    else
+        echo "${test_case} skip"
+    fi
 
+}
+
+
+##stress-ng function
+lava_test_result_stress_ng() {
+    exit_code="$?"
+    [ "$#" -lt 1 ] && error_msg "Usage: lava_test_result test_case output"
+    test_case="$1"
+    output="$2"
+
+    which lava-test-runner
+    test_lava=$?
+    if [ "${test_lava}" -eq 0 ]; then
+        lava_check="true"
+    else
+        lava_check="false"
+    fi 
+
+    if [ -n "${output}" ]; then 
+        if [ "${output}" -gt 0 ];then
+            if [ "${lava_check}" = "true" ];then
+                lava-test-case ${test_case} --result pass
+            else
+                echo "${test_case} test passed"
+            fi
+        else
+            if [ "${lava_check}" = "true" ];then
+                lava-test-case ${test_case} --result fail 
+                exit 0
+            else
+                echo "${test_case} test failed"
+                exit 0
+
+            fi
+        fi
+    else
+        if [ "${lava_check}" = "true" ];then
+                echo "Usage: lava_test_result test_case output"
+                lava-test-case ${test_case} --result fail 
+                exit 0
+            else
+                echo "Usage: lava_test_result test_case output"
+                echo "${test_case} test failed"
+                exit 0
+
+            fi
+    fi
 }
